hl.config({ autogenerated = false })

--- monitor
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "1",
})

--- env variables
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("LC_TIME", "es_CL.UTF-8")

--- programs
local terminal = "kitty"
local menu = "rofi -show drun"
local filemanager = "dolphin"

--- startup programs
hl.on("hyprland.start", function ()
	hl.exec_cmd("hyprlock --grace 0 & awww-daemon & hypridle & hyprpanel & wl-clip-persist --clipboard both & wl-paste --watch cliphist store & systemctl --user start hyprpolkitagent & dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP & gnome-keyring-daemon --start --components=secrets,pkcs11 & ~/.config/hypr/scripts/hypr-brave-unfullscreen-fix & hyprswitch init & ~/.config/hypr/scripts/pip-window-escape & udiskie & ~/.scripts.local/hypr-extras")
end)

--- layout
hl.config({
	input = {
		kb_layout = "latam",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		repeat_delay = 250,
		repeat_rate = 45,
		follow_mouse = 2,
		sensitivity = 0,
		touchpad = {
			natural_scroll = true,
			tap_to_click = true,
			disable_while_typing = true
		}
	}
})

--- device
hl.device({
	name = "elan0676:00-04f3:3195-touchpad",
	sensitivity = -0.5,
})

--- general and decoration
hl.config({
	general = {
		layout = "dwindle",
		gaps_in = 3,
		gaps_out = 4,
		border_size = 2,
		col = {
			active_border = "rgba(d4a0b9ee)",
			inactive_border = "rgba(313244aa)"
		}
	},
	decoration = {
		rounding = 4,
		rounding_power = 2,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 10,
			render_power = 3,
			color = "rgba(1a1a2eee)",
		},
		blur = {
			enabled = true,
			size = 5,
			passes = 2,
		},
	},
	animations = {
		enabled = true,
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		focus_on_activate = true,
	},
})

--- dwindle and ecosystem
hl.config({
	dwindle = {
		preserve_split = true,
		force_split = 2
	},
	ecosystem = {
		no_update_news = true
	},
	render = {
		commit_timing_enabled = false,
	}
})

--- animations
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })
hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

--- window rules
hl.window_rule({
	match = { class = "steam_app_", fullscreen = true },
	immediate = true,
})
hl.window_rule({
	match = { class = "steam" },
	float = true,
	min_size = {1, 1},
	stay_focused = true,
})
hl.window_rule({
	match = { class = "pavucontrol" },
	float = true,
})
hl.window_rule({
	match = { class = "blueman-manager" },
	float = true,
}) 
hl.window_rule({
	match = { initial_title = "Open File" },
	float = true, 
})
hl.window_rule({
	match = { initial_title = "Save File" },
	float = true,
})
hl.window_rule({
	match = { initial_title = "Picture in picture" },
	float = true,	
})
hl.window_rule({
	match = { initial_title = "Picture in picture" },
	pin = true,
})
hl.window_rule({
	match = { class = "gsimplecal" },
	pin = true,
	move = "1080 35",
	float = true,
})

--- chats app
hl.window_rule({
	match = { class = "Slack" }, 
    workspace = "1 silent",
})
hl.window_rule({
	match = { class = "signal" }, 
    workspace = "1 silent"
})
hl.window_rule({
	match = { class = "com.rtosta.zapzap" }, 
    workspace = "1 silent"
})
hl.window_rule({
  	match = { class = "brave-akpamiohjfcnimfljfndmaldlcfphjmp-Default" }, 
    workspace = "1 silent",
})

--- Pip terminal
hl.window_rule({
	match = { class = "pipterm" }, 
    workspace = "special:pip",
	float = true
})
hl.window_rule({
 	match = { class = "Spotify" },
    workspace = "special:pipspoti",
 	float = true
})

--- keybinds
local mainMod = "SUPER"
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-chats"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("~/.config/hypr/scripts/pipspotify"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-3columns"))
hl.bind(mainMod .. " + BackSpace", hl.dsp.exec_cmd("~/.config/hypr/scripts/pipterm"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("rofimoji --selector rofi --action type"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(filemanager))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd([[sh -c 'printf "LSFG_LEGACY=1 LSFG_MULTIPLIER=2 %%command%%" | wl-copy && notify-send "lsfg-vk" "LSFG_LEGACY=1 LSFG_MULTIPLIER=2 %%command%%\n(copiado al portapapeles)"']]))

-- Screenshots
hl.bind("Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-screenshot area"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-screenshot window"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-screenshot full"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-screenshot ocr"))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind(mainMod .. " + SHIFT + Escape", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-wlogout"))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd([[sh -c "pkill -9 -f 'gjs.*-ags\\.js'; pkill -9 -x hyprpanel-app; sleep 1; hyprctl dispatch exec hyprpanel"]]))

-- Brillo (notebook)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))

-- Teclas de volumen
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind(mainMod .. " + Left", hl.dsp.exec_cmd("playerctl -p spotify previous"))
hl.bind(mainMod .. " + Down", hl.dsp.exec_cmd("playerctl -p spotify play-pause"))
hl.bind(mainMod .. " + Right", hl.dsp.exec_cmd("playerctl -p spotify next"))

-- Foco entre ventanas (mismo espacio de trabajo)
hl.bind(mainMod .. " + h", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-smartfocus l"))
hl.bind(mainMod .. " + j", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-smartfocus d"))
hl.bind(mainMod .. " + k", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-smartfocus u"))
hl.bind(mainMod .. " + l", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-smartfocus r"))

-- Cambiar escritorio (horizontal)
hl.bind(mainMod .. " + CTRL + h", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-switchws -1"))
hl.bind(mainMod .. " + CTRL + l", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-switchws +1"))
--- move through workspace
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1}))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2}))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3}))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4}))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5}))
hl.bind(mainMod .. " + SHIFT + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + " .. 5, hl.dsp.window.move({ workspace = 5 }))

-- scrol through workspace with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-switchws -1"))
hl.bind(mainMod .. " + mouse_up", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-switchws +1"))
hl.bind(mainMod .. " + CTRL + Tab", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-switchws +1"))
hl.bind(mainMod .. " + CTRL + SHIFT + Tab", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-switchws -1"))
hl.bind(mainMod .. " + SHIFT + mouse_up", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movewindow r"))
hl.bind(mainMod .. " + SHIFT + mouse_down", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movewindow l"))

-- Mover ventana: intercambiar en el mismo espacio o mover a escritorio adyacente
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movewindow l"))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movewindow d"))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movewindow u"))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movewindow r"))

-- Selector de ventanas
hl.bind("ALT + Tab", hl.dsp.exec_cmd("hyprswitch gui --mod-key alt --key tab --close mod-key-release --sort-recent"))
hl.bind("ALT + SHIFT + Tab", hl.dsp.exec_cmd("hyprswitch gui --mod-key alt --key tab --reverse-key=mod=shift --close mod-key-release --sort-recent"))
hl.bind(mainMod .. " + Tab", hl.dsp.exec_cmd("rofi -show window"))
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-keybinds"))

-- Navegación de monitores
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + ALT + SHIFT + h", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movetomonitor l"))
hl.bind(mainMod .. " + ALT + SHIFT + j", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movetomonitor d"))
hl.bind(mainMod .. " + ALT + SHIFT + k", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movetomonitor u"))
hl.bind(mainMod .. " + ALT + SHIFT + l", hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-movetomonitor r"))

-- Redimensionar con el ratón
-- hl.bind(mainMod .. " + mouse:272", hl.dsp.movewindow())
-- hl.bind(mainMod .. " + mouse:273", hl.dsp.resizewindow())
