general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd = hyprctl dispatch dpms on; sleep 1 && hyprpanel -q; hyprpanel &
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Turn off screen 5 seconds after idle (only while locked)
listener {
    timeout = 60
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
